# Generated by Django 4.0.3 on 2023-03-31 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advocates_roll_number',
            fields=[
                ('roll_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='charge_sheet',
            fields=[
                ('accused', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('charges', models.TextField()),
                ('offense_description', models.TextField()),
                ('other_accused', models.CharField(default=None, max_length=50, null=True)),
                ('evidence', models.TextField(default=None, null=True)),
                ('penalties', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='clients_id',
            fields=[
                ('client_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='demand_letter',
            fields=[
                ('sender', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('recipient', models.CharField(max_length=50)),
                ('demand', models.TextField()),
                ('deadline', models.DateField()),
                ('documents', models.TextField()),
                ('statement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='case',
            fields=[
                ('demand_letter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='court_system.demand_letter')),
                ('charge_sheet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='court_system.charge_sheet')),
                ('case_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pre_trial_date', models.DateField()),
                ('trial_date', models.DateField()),
                ('decision_date', models.DateField()),
                ('issuance_of_decree', models.TextField(default=None, null=True)),
                ('enforcement', models.TextField(default=None, null=True)),
            ],
            bases=('court_system.charge_sheet', 'court_system.demand_letter'),
        ),
        migrations.CreateModel(
            name='lawyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('availability', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('won', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('roll_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='court_system.advocates_roll_number')),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='court_system.clients_id')),
            ],
        ),
    ]
