# Generated by Django 4.0.3 on 2023-04-13 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('court_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cases_instances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='courts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name='charge_sheet_ptr',
        ),
        migrations.RemoveField(
            model_name='case',
            name='demand_letter_ptr',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lawyers',
            name='lost',
        ),
        migrations.RemoveField(
            model_name='lawyers',
            name='won',
        ),
        migrations.AddField(
            model_name='case',
            name='charge_sheet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='court_system.charge_sheet', unique=True),
        ),
        migrations.AddField(
            model_name='case',
            name='demand_letter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='court_system.demand_letter', unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='cases',
            field=models.ManyToManyField(through='court_system.cases_instances', to='court_system.case'),
        ),
        migrations.AddField(
            model_name='clients_id',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='demand_letter',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawyers',
            name='cases',
            field=models.ManyToManyField(through='court_system.cases_instances', to='court_system.case'),
        ),
        migrations.AlterField(
            model_name='demand_letter',
            name='sender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='court_system.clients_id'),
        ),
        migrations.AddField(
            model_name='cases_instances',
            name='cases',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='court_system.case'),
        ),
        migrations.AddField(
            model_name='cases_instances',
            name='client',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='court_system.client'),
        ),
        migrations.AddField(
            model_name='cases_instances',
            name='lawyer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='court_system.lawyers'),
        ),
        migrations.AddField(
            model_name='case',
            name='court',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='court_system.courts'),
        ),
    ]
