# Generated by Django 4.2 on 2023-10-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('court_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge_sheet',
            name='penalties',
        ),
    ]
