# Generated by Django 4.2 on 2023-10-01 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('court_system', '0002_remove_charge_sheet_penalties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='enforcement',
        ),
        migrations.RemoveField(
            model_name='case',
            name='issuance_of_decree',
        ),
    ]
