# Generated by Django 4.2 on 2023-09-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_system', '0002_auto_20230927_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients_id',
            name='client_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
