# Generated by Django 4.0.3 on 2023-04-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_system', '0003_remove_lawyers_name_advocates_roll_number_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyers',
            name='phone_number',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
